src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use App\Entity\Traits\Timestampable;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="users")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(fields={"email"}, message="Il existe déjà un compte avec cet e-mail")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    use Timestampable;
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Ce champ est requis")
     * @Assert\Length(min = 3, minMessage = "Le prénom doit avoir au minimun {{ limit }} caractères")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Ce champ est requis")
     * @Assert\Length(min = 2, minMessage = "Le prénom doit avoir au minimun {{ limit }} caractères")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank(message="Ce champ est requis")
     * @Assert\Email(message = "Ce mail '{{ value }}' n'est pas valide.")
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Festival::class, mappedBy="user", orphanRemoval=true)
     */
    private $festivals;

    /**
     * @ORM\OneToMany(targetEntity=Blogpost::class, mappedBy="user", orphanRemoval=true)
     */
    private $blogposts;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="user", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity=Contact::class, mappedBy="user", orphanRemoval=true)
     */
    private $contacts;

    /**
     * @ORM\OneToMany(targetEntity=Inscription::class, mappedBy="user", orphanRemoval=true)
     */
    private $inscriptions;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Ce champ est requis")
     */
    private $phoneNumber;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    public function getFullName()
    {
        return $this->getFirstName() . ' ' . $this->getLastName();
    }

    public function getGravatarUrl(?int $size = 100)
    {
       return sprintf('https://www.gravatar.com/avatar/%s?s=%d', md5( strtolower( trim($this->getEmail()) ) ), $size);
    }

    public function __toString()
    {
        return $this->firstName;
    }

    public function __construct()
    {
        $this->festivals = new ArrayCollection();
        $this->blogposts = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->contacts = new ArrayCollection();
        $this->inscriptions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Festival[]
     */
    public function getFestivals(): Collection
    {
        return $this->festivals;
    }

    public function addFestival(Festival $festival): self
    {
        if (!$this->festivals->contains($festival)) {
            $this->festivals[] = $festival;
            $festival->setUser($this);
        }

        return $this;
    }

    public function removeFestival(Festival $festival): self
    {
        if ($this->festivals->removeElement($festival)) {
            // set the owning side to null (unless already changed)
            if ($festival->getUser() === $this) {
                $festival->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Blogpost[]
     */
    public function getBlogposts(): Collection
    {
        return $this->blogposts;
    }

    public function addBlogpost(Blogpost $blogpost): self
    {
        if (!$this->blogposts->contains($blogpost)) {
            $this->blogposts[] = $blogpost;
            $blogpost->setUser($this);
        }

        return $this;
    }

    public function removeBlogpost(Blogpost $blogpost): self
    {
        if ($this->blogposts->removeElement($blogpost)) {
            // set the owning side to null (unless already changed)
            if ($blogpost->getUser() === $this) {
                $blogpost->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Contact[]
     */
    public function getContacts(): Collection
    {
        return $this->contacts;
    }

    public function addContact(Contact $contact): self
    {
        if (!$this->contacts->contains($contact)) {
            $this->contacts[] = $contact;
            $contact->setUser($this);
        }

        return $this;
    }

    public function removeContact(Contact $contact): self
    {
        if ($this->contacts->removeElement($contact)) {
            // set the owning side to null (unless already changed)
            if ($contact->getUser() === $this) {
                $contact->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Inscription[]
     */
    public function getInscriptions(): Collection
    {
        return $this->inscriptions;
    }

    public function addInscription(Inscription $inscription): self
    {
        if (!$this->inscriptions->contains($inscription)) {
            $this->inscriptions[] = $inscription;
            $inscription->setUser($this);
        }

        return $this;
    }

    public function removeInscription(Inscription $inscription): self
    {
        if ($this->inscriptions->removeElement($inscription)) {
            // set the owning side to null (unless already changed)
            if ($inscription->getUser() === $this) {
                $inscription->setUser(null);
            }
        }

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

templates/layouts/partials/_flash_messages.html.twig
<div aria-live="polite" aria-atomic="true">
    <div class="toast-container position-absolute p-3 bottom-0 end-0" style="z-index: 99999999;">
        {% for type, messages in app.flashes %}
            {% for message in messages %}
                <div class="toast bg-{{ type }} text-white d-flex align-items-center" role="alert" 
                    aria-live="assertive" aria-atomic="true">
                    <div class="toast-body">
                        {{ message }}
                    </div>
                    <button type="button" class="btn-close btn-close-white ms-auto me-2" 
                        data-bs-dismiss="toast" aria-label="Close">
                    </button>
                </div>
            {% endfor %}
        {% endfor %}
    </div>
</div>


<!-- <div class="container mt-2 text-center"> 
    {#{% for type, messages in app.flashes %}
        {% for message in messages %}
            <div class="alert alert-{{ type }} alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endfor %}#}
</div> -->

templates/layouts/partials/_footer.html.twig
<footer class="mt-4 pt-5 pb-5 bg-dark">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-4 col-lg-3">
                <h1 class="mb-2 text-muted fw-bolder display-4">
                    FestiTobli
                </h1>
                <p class="text-white mb-2">
                    Le séjour dans l'eau ne transforme pas un tronc d'arbre en crocodile.
                    Always be yourself!
                </p>
            </div>
            <div class="col-12 col-md-4 col-lg-2">
                <h6 class="text-bold text-uppercase text-white">
                    Menu
                </h6>
                <ul class="list-unstyled text-muted mb-6 mb-mb-8 mb-lg-0">
                    <li class="mb-3">
                        <a  class="text-reset text-decoration-none" href="{{ path('app_festivals_index') }}">
                            Nos festivals
                        </a>
                    </li>
                    <li class="mb-3">
                        <a  class="text-reset text-decoration-none" href="{{ path('app_blogposts_index') }}">
                            Nos articles
                        </a>
                    </li>
                    <li class="mb-3">
                        <a  class="text-reset text-decoration-none" href="{{ path('app_contact') }}">
                            Nous contacter
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-12 col-md-4 col-lg-4">
                <h6 class="text-bold text-uppercase text-white">
                    Informations
                </h6>
                <p class="text-muted mb-2">
                    FestiTobli est une application web qui permet de mettre en valeur la culture malienne,
                    à travers les différents festivals et activités culturelles organisés au Mali tout au long de 
                    l'année.
                </p>
                <p class="text-muted mb-2">
                    Le blog FestiTobli vous permet de voyager au fin fond du Mali pour découvrir des choses insoupçonnées.  
                </p>
            </div>
            <div class="col-12 col-md-4 col-lg-2">
                <h6 class="text-bold text-uppercase text-white">
                    Mentions légales
                </h6>
                <ul class="list-unstyled text-muted mb-0">
                    <li class="mb-3">
                        <a  class="text-reset text-decoration-none" href="">
                            TobliCorp
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

templates/layouts/partials/_nav.html.twig
<nav class="navbar navbar-expand-lg navbar-light bg-light" aria-label="Third navbar example">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ path('app_home') }}"><img src="{{ asset('build/icones/festitobli.png') }}" alt="Icone FestiTobli" class="img-fluid"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExample03">
            <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ path('app_festivals_index') }}">
                        <img src="{{ asset('build/icones/nosfestivals1.png') }}" alt="Icone FestiTobli" class="img-fluid">
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ path('app_blogposts_index') }}">
                        <img src="{{ asset('build/icones/nosarticles1.png') }}" alt="Icone FestiTobli" class="img-fluid">
                    </a>
                </li>
            </ul>
                {% if app.user %}
                    <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-bs-toggle="dropdown" aria-expanded="false">
                                <img src="{{ app.user.gravatarUrl(30) }}" alt="Avatar de {{ app.user.fullName }}" class="shadow rounded-circle">
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="dropdown03">
                                <li><a class="dropdown-item" href="{{ path('app_dashboard') }}">Tableau de bord</a></li>
                                <li><a class="dropdown-item" href="{{ path('app_account') }}">Paramètre du compte</a></li>
                                <li><a class="dropdown-item" href="{{ path('app_contact') }}">Nous contacter</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li>
                                    <a class="dropdown-item" href="#" onclick="event.preventDefault(); 
                                    document.getElementById('js-logout-form').submit();">
                                        Se déconnecter
                                    </a>
                                </li>
                                <form id="js-logout-form" action="{{ path('app_logout') }}" method="POST" style="display: none">
                                    <input type="hidden" name="_csrf_token" value="{{ csrf_token('logout') }}">
                                </form>
                            </ul>
                        </li>
                    </ul>
                {% else %}
                    <ul class="navbar-nav d-inline-flex mt-2 mt-md-0 ms-md-auto">
                        <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ path('app_register') }}">
                            <img src="{{ asset('build/icones/senregistrer.png') }}" alt="Icone FestiTobli" class="img-fluid">
                        </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ path('app_login')}}">
                                <img src="{{ asset('build/icones/seconnecter.png') }}" alt="Icone FestiTobli" class="img-fluid">
                            </a>
                        </li>
                    </ul>
                {% endif %}
        </div>
    </div>
</nav>